services:
  vikunja:
    image: vikunja/vikunja:latest

    environment:
      VIKUNJA_SERVICE_PUBLICURL: http://localhost:3456/

      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_USER: ${POSTGRES_USER}
      VIKUNJA_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      VIKUNJA_DATABASE_DATABASE: ${POSTGRES_DB}

      VIKUNJA_SERVICE_SECRET: ${VIKUNJA_SECRET}

    ports:
      - "3456:3456"

    volumes:
      - ./files:/app/vikunja/files

    depends_on:
      db:
        condition: service_healthy

    restart: unless-stopped


  db:
    image: postgres:18

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - ./db:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER"]
      interval: 2s
      start_period: 30s

    restart: unless-stopped
